# Netlify Build Settings
[build]
  command = "npm install --omit=optional && npm run build"
  publish = "dist"

# Netlify Forms - Enable form handling
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--omit=optional"

# Plugins
[[plugins]]
  package = "@netlify/plugin-forms"
