# Netlify Build Settings
[build]
  command = "npm ci --omit=optional || npm install --omit=optional && npm run build"
  publish = "dist"

# Netlify Forms - Enable form handling
[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--omit=optional"
  NPM_CONFIG_OPTIONAL = "false"
